language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

# Get AAF-devel libs

env:
    - AAF_ROOT=AAF-devel

before_install:
    - mkdir AAF-devel
    - cd AAF-devel
    - wget http://sourceforge.net/projects/aaf/files/AAF-devel-libs/1.1.6/AAF-devel-libs-x86_64Linux-1.1.6.0.tar.gz
    - tar -xvf AAF-devel-libs-x86_64Linux-1.1.6.0.tar.gz
    - cd ..
    # install newer version of ffmpeg
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq ffmpeg
    - wget http://ffmpeg.org/releases/ffmpeg-1.2.2.tar.bz2
    - tar -xf ffmpeg-1.2.2.tar.bz2
    - cd ffmpeg-1.2.2
    # disable stuff we don't need only using ffmpeg for dv, dnxhd and audio encoding
    - ./configure --disable-doc
    - make
    - sudo make install
    - cd ..
    
# Install build requirements.
install: pip install cython

script:
    - make install
    - make test
